export const allStations = [
  "ABM",
  "ALT",
  "ANC",
  "ASM",
  "ASW",
  "ASH",
  "AUD",
  "BAG",
  "BMR",
  "EVC",
  "BCH",
  "BOB",
  "BKV",
  "BDW",
  "BRK",
  "BRT",
  "BRY",
  "CER",
  "CEP",
  "CHO",
  "CLA",
  "CNK",
  "CRO",
  "CRP",
  "DAN",
  "GMX",
  "DER",
  "DDV",
  "DYL",
  "EDD",
  "ECC",
  "EDL",
  "SPC",
  "EXQ",
  "EXS",
  "FAL",
  "FIR",
  "FRE",
  "HBC",
  "HPK",
  "HOL",
  "HOT",
  "IWM",
  "KIN",
  "LDW",
  "LGW",
  "AIR",
  "MKT",
  "MAR",
  "MEC",
  "MIL",
  "MON",
  "MRD",
  "NAV",
  "NIS",
  "NEB",
  "NEH",
  "NHM",
  "NMR",
  "OLD",
  "OHC",
  "OHK",
  "OHM",
  "PAR",
  "PLH",
  "PIC",
  "PCG",
  "POM",
  "PRS",
  "QNS",
  "RAD",
  "RBN",
  "ROC",
  "RTC",
  "RTH",
  "SAL",
  "SWP",
  "SFQ",
  "SHD",
  "SHC",
  "SHL",
  "SOC",
  "SPS",
  "SWR",
  "STR",
  "TRC",
  "TMP",
  "TFB",
  "VEL",
  "VIC",
  "VLG",
  "WST",
  "WDD",
  "WWD",
  "WSD",
  "WFD",
  "WTH",
  "WPK",
  "WYC",
];

export const allTerminus = [
  "ECC",
  "AIR",
  "RTC",
  "ALT",
  "ASH",
  "SHC",
  "EDD",
  "TRC",
  "BRY",
  "MEC",
  "PIC",
  "VIC",
];

export const codeToDestination = (destination: string): string => {
  const map = {
    ABM: "Abraham Moss",
    ALT: "Altrincham",
    ANC: "Anchorage",
    ASM: "Ashton Moss",
    ASW: "Ashton West",
    ASH: "Ashton-Under-Lyne",
    AUD: "Audenshaw",
    BAG: "Baguley",
    BMR: "Barlow Moor Road",
    EVC: "Barton Dock Road",
    BCH: "Benchill",
    BOB: "Besses O’ Th’ Barn",
    BKV: "Bowker Vale",
    BDW: "Broadway",
    BRK: "Brooklands",
    BRT: "Burton Road",
    BRY: "Bury",
    CER: "Cemetery Road",
    CEP: "Central Park",
    CHO: "Chorlton",
    CLA: "Clayton Hall",
    CNK: "Cornbrook",
    CRO: "Crossacres",
    CRP: "Crumpsall",
    DAN: "Dane Road",
    GMX: "Deansgate - Castlefield",
    DER: "Derker",
    DDV: "Didsbury Village",
    DYL: "Droylsden",
    EDD: "East Didsbury",
    ECC: "Eccles",
    EDL: "Edge Lane",
    SPC: "Etihad Campus",
    EXQ: "Exchange Quay",
    EXS: "Exchange Square",
    FAL: "Failsworth",
    FIR: "Firswood",
    FRE: "Freehold",
    HBC: "Harbour City",
    HPK: "Heaton Park",
    HOL: "Hollinwood",
    HOT: "Holt Town",
    IWM: "Imperial War Museum",
    KIN: "Kingsway Business Park",
    LDW: "Ladywell",
    LGW: "Langworthy",
    AIR: "Manchester Airport",
    MKT: "Market Street",
    MAR: "Martinscroft",
    MEC: "MediacityUK",
    MIL: "Milnrow",
    MON: "Monsall",
    MRD: "Moor Road",
    NAV: "Navigation Road",
    NIS: "New Islington",
    NEB: "Newbold",
    NEH: "Newhey",
    NHM: "Newton Heath and Moston",
    NMR: "Northern Moor",
    OLD: "Old Trafford",
    OHC: "Oldham Central",
    OHK: "Oldham King Street",
    OHM: "Oldham Mumps",
    PAR: "Parkway",
    PLH: "Peel Hall",
    PIC: "Piccadilly",
    PCG: "Piccadilly Gardens",
    POM: "Pomona",
    PRS: "Prestwich",
    QNS: "Queens Road",
    RAD: "Radcliffe",
    RBN: "Robinswood Road",
    ROC: "Rochdale Railway Station",
    RTC: "Rochdale Town Centre",
    RTH: "Roundthorn",
    SAL: "Sale",
    SWP: "Sale Water Park",
    SFQ: "Salford Quays",
    SHD: "Shadowmoss",
    SHC: "Shaw and Crompton",
    SHL: "Shudehill",
    SOC: "South Chadderton",
    SPS: "St. Peter's Square",
    SWR: "St Werburgh’s Road",
    STR: "Stretford",
    TRC: "The Trafford Centre",
    TMP: "Timperley",
    TFB: "Trafford Bar",
    VEL: "Velopark",
    VIC: "Victoria",
    VLG: "Village",
    WST: "Weaste",
    WDD: "West Didsbury",
    WWD: "Westwood",
    WSD: "Wharfside",
    WFD: "Whitefield",
    WTH: "Withington",
    WPK: "Wythenshawe Park",
    WYC: "Wythenshawe Town Centre",
  };
  return map[destination] || "";
};

export const destinationToCode = (destination: string): string => {
  const map = {
    "Abraham Moss": "ABM",
    Altrincham: "ALT",
    Anchorage: "ANC",
    "Ashton Moss": "ASM",
    "Ashton West": "ASW",
    "Ashton-under-Lyne": "ASH",
    "Ashton-Under-Lyne": "ASH",
    Audenshaw: "AUD",
    Baguley: "BAG",
    "Barlow Moor Road": "BMR",
    "Barton Dock Road": "EVC",
    Benchill: "BCH",
    "Besses O’ Th’ Barn": "BOB",
    "Bowker Vale": "BKV",
    Broadway: "BDW",
    Brooklands: "BRK",
    "Burton Road": "BRT",
    Bury: "BRY",
    "Cemetery Road": "CER",
    "Central Park": "CEP",
    Chorlton: "CHO",
    "Clayton Hall": "CLA",
    Cornbrook: "CNK",
    Crossacres: "CRO",
    Crumpsall: "CRP",
    "Dane Road": "DAN",
    "Deansgate - Castlefield": "GMX",
    Derker: "DER",
    "Didsbury Village": "DDV",
    Droylsden: "DYL",
    "East Didsbury": "EDD",
    Eccles: "ECC",
    "Eccles via MediaCityUK": "ECC",
    "Edge Lane": "EDL",
    "Etihad Campus": "SPC",
    "Exchange Quay": "EXQ",
    "Exchange Square": "EXS",
    Failsworth: "FAL",
    Firswood: "FIR",
    Freehold: "FRE",
    "Harbour City": "HBC",
    "Heaton Park": "HPK",
    Hollinwood: "HOL",
    "Holt Town": "HOT",
    "Imperial War Museum": "IWM",
    "Kingsway Business Park": "KIN",
    Ladywell: "LDW",
    Langworthy: "LGW",
    "Manchester Airport": "AIR",
    "Market Street": "MKT",
    Martinscroft: "MAR",
    MediacityUK: "MEC",
    Milnrow: "MIL",
    Monsall: "MON",
    "Moor Road": "MRD",
    "Navigation Road": "NAV",
    "New Islington": "NIS",
    Newbold: "NEB",
    Newhey: "NEH",
    "Newton Heath and Moston": "NHM",
    "Northern Moor": "NMR",
    "Old Trafford": "OLD",
    "Oldham Central": "OHC",
    "Oldham King Street": "OHK",
    "Oldham Mumps": "OHM",
    Parkway: "PAR",
    "Peel Hall": "PLH",
    Piccadilly: "PIC",
    "Piccadilly Gardens": "PCG",
    Pomona: "POM",
    Prestwich: "PRS",
    "Queens Road": "QNS",
    Radcliffe: "RAD",
    "Robinswood Road": "RBN",
    "Rochdale Railway Station": "ROC",
    "Rochdale Town Centre": "RTC",
    Roundthorn: "RTH",
    Sale: "SAL",
    "Sale Water Park": "SWP",
    "Salford Quays": "SFQ",
    Shadowmoss: "SHD",
    "Shaw and Crompton": "SHC",
    Shudehill: "SHL",
    "South Chadderton": "SOC",
    "St. Peter's Square": "SPS",
    "St Werburgh’s Road": "SWR",
    Stretford: "STR",
    "The Trafford Centre": "TRC",
    Timperley: "TMP",
    "Trafford Bar": "TFB",
    Velopark: "VEL",
    Victoria: "VIC",
    Village: "VLG",
    Weaste: "WST",
    "West Didsbury": "WDD",
    Westwood: "WWD",
    Wharfside: "WSD",
    Whitefield: "WFD",
    Withington: "WTH",
    "Wythenshawe Park": "WPK",
    "Wythenshawe Town Centre": "WYC",
  };
  return map[destination] || "";
};

export const codeToPath = (code) => {
  const map = {
    ABM: "abraham-moss",
    ALT: "altrincham",
    ANC: "anchorage",
    ASM: "ashton-moss",
    ASW: "ashton-west",
    ASH: "ashton-under-lyne",
    AUD: "audenshaw",
    BAG: "baguley",
    BMR: "barlow-moor-road",
    EVC: "barton-dock-road",
    BCH: "benchill",
    BOB: "besses-o-th-barn",
    BKV: "bowker-vale",
    BDW: "broadway",
    BRK: "brooklands",
    BRT: "burton-road",
    BRY: "bury",
    CER: "cemetery-road",
    CEP: "central-park",
    CHO: "chorlton",
    CLA: "clayton-hall",
    CNK: "cornbrook",
    CRO: "crossacres",
    CRP: "crumpsall",
    DAN: "dane-road",
    GMX: "deansgate-castlefield",
    DER: "derker",
    DDV: "didsbury-village",
    DYL: "droylsden",
    EDD: "east-didsbury",
    ECC: "eccles",
    EDL: "edge-lane",
    SPC: "etihad-campus",
    EXQ: "exchange-quay",
    EXS: "exchange-square",
    FAL: "failsworth",
    FIR: "firswood",
    FRE: "freehold",
    HBC: "harbour-city",
    HPK: "heaton-park",
    HOL: "hollinwood",
    HOT: "holt-town",
    IWM: "imperial-war-museum",
    KIN: "kingsway-business-park",
    LDW: "ladywell",
    LGW: "langworthy",
    AIR: "manchester-airport",
    MKT: "market-street",
    MAR: "martinscroft",
    MEC: "mediacityuk",
    MIL: "milnrow",
    MON: "monsall",
    MRD: "moor-road",
    NAV: "navigation-road",
    NIS: "new-islington",
    NEB: "newbold",
    NEH: "newhey",
    NHM: "newton-heath-and-moston",
    NMR: "northern-moor",
    OLD: "old-trafford",
    OHC: "oldham-central",
    OHK: "oldham-king-street",
    OHM: "oldham-mumps",
    PAR: "parkway",
    PLH: "peel-hall",
    PIC: "piccadilly",
    PCG: "piccadilly-gardens",
    POM: "pomona",
    PRS: "prestwich",
    QNS: "queens-road",
    RAD: "radcliffe",
    RBN: "robinswood-road",
    ROC: "rochdale-railway-station",
    RTC: "rochdale-town-centre",
    RTH: "roundthorn",
    SAL: "sale",
    SWP: "sale-water-park",
    SFQ: "salford-quays",
    SHD: "shadowmoss",
    SHC: "shaw-and-crompton",
    SHL: "shudehill",
    SOC: "south-chadderton",
    SPS: "st-peters-square",
    SWR: "st-werburghs-road",
    STR: "stretford",
    TRC: "the-trafford-centre",
    TMP: "timperley",
    TFB: "trafford-bar",
    VEL: "velopark",
    VIC: "victoria",
    VLG: "village",
    WST: "weaste",
    WDD: "west-didsbury",
    WWD: "westwood",
    WSD: "wharfside",
    WFD: "whitefield",
    WTH: "withington",
    WPK: "wythenshawe-park",
    WYC: "wythenshawe-town-centre",
  };
  return map[code];
};
