org: cdavies93
app: metro-api
service: metro-api
frameworkVersion: '3'
useDotenv: true

plugins:
  - serverless-plugin-typescript
  - serverless-dotenv-plugin

custom:
  enterprise:
    collectLambdaLogs: false
    disableAwsSpans: true
    disableHttpSpans: true

provider:
  name: aws
  runtime: nodejs14.x
  region: eu-west-2
  stage: dev
  environment:
    TFGM_KEY: ${env:TFGM_KEY}
    environment: ${opt:stage, self:provider.stage}
  iam:
    role:
      statements:
        - Effect: Allow
          Action: 's3:ListBucket'
          Resource: '*'
        - Effect: Allow
          Action:
            - 's3:GetObject'
            - 's3:PutObject'
            - 's3:ListObjects'
          Resource:
            - 'arn:aws:s3:::first-and-last-trams-dev/*'
        - Effect: "Allow"
          Action:
            - "cloudwatch:PutMetricData"
          Resource: "*"

functions:
  station:
    handler: handler.station
    events:
      - httpApi:
          path: /{stationId}
          method: get
      - schedule: rate(1 minute)
  firstAndLast:
    handler: handler.firstAndLast
    events:
      - schedule: rate(1 hour)
