org: cdavies93
app: metro-api
service: metro-api
frameworkVersion: '3'
useDotenv: true

plugins:
  - serverless-plugin-typescript
  - serverless-dotenv-plugin

provider:
  name: aws
  runtime: nodejs14.x
  region: eu-west-2
  stage: dev
  environment:
    TFGM_KEY: ${env:TFGM_KEY}
    environment: ${opt:stage, self:provider.stage}

  iamRoleStatements:
    - Effect: "Allow"
      Action:
       - "s3:*"
      Resource: { "Fn::Join": ["", ["arn:aws:s3:::first-and-last-trams-dev", "/*" ] ] }


functions:
  station:
    handler: handler.station
    events:
      - httpApi:
          path: /{stationId}
          method: get
  firstAndLast:
    handler: handler.firstAndLast
    events:
      - schedule: rate(10 minutes)
