org: cdavies93
app: metro-api
service: metro-api
frameworkVersion: '3'

plugins:
  - serverless-plugin-typescript

provider:
  name: aws
  runtime: nodejs14.x
  region: eu-west-2
  stage: dev

functions:
  station:
    handler: handler.station
    events:
      - httpApi:
          path: /{stationId}
          method: get
